### PR TITLE
Fix: housecleanup.sqf. Medic gear/licenses. House sellbuy-dupe, Civ info

### PR DESCRIPTION
**Pull request by hitem**
--MEDIC GEAR/LICENSES--
I added a fix for the medics (their clothing/licenses where saving in the wrong columns (for cops)) so it broke the cop login as they had mediclicenses as gear. Make sure the number %4 and %5 is corresponding with med_gear and med_licenses in your database, else switch them around.

--CIVINFO--
Returns arrested without -string to it. As arrested is a 1 or 0. Solves some RPT errors for me regarding Arrested/getting stuck on loading into the server. And also, everywhere else in the ExtDB ini its used w/o -string, i think this fix was mentioned on the forums to! 

--HOUSE SELL/BUY DUPE FIX--
Also a fix for the houses. When they are sold and bought the same restart, people get the inventory of the boxes when they place new cargoboxes (if it happens same restart, thats a MAJOR dupe source). With this fix you dont have that issue anymore as the sell querys will wipe inventory and boxes to so when they are bought, they are truly empty.

--HOUSECLEANUP ERROR--
Ive had alot of issues when people disconnect from the server. 
(Edit: In my database the houses are populated)
The RPT errors is referring to:

File life_server\Functions\MySQL\fn_asyncCall.sqf, line 62
Error Invalid number in expression
File life_server\Functions\Housing\fn_houseCleanup.sqf, line 12
Error Undefined variable in expression: _houses

And this is how i solved it, i simply added the sql output to the
[housecleanup] array in altis-life-rpg-4.ini as the fn_housecleanup.sqf
is expecting a value, with no strange things in it, in return. The array looks the same as
[housingFetchPlayerHouse] so i guess its also possible to point towards
that one, but lets try to do it right! If this is right that is! :) . 

This is my try to contribute with something after spending tons of late nights on this! thanks
itsyuka for everything and ofc tonic and those around helping!

### CODE REVIEW

**Comment by Provokan** [comment]
can u fix this  ??

[02:02:52 +02:00] [Thread 3040289625] extDB: DB_CUSTOM_V5: Error No Custom Call Not Found: Input String SELECT pid, pos, inventory, containers FROM houses WHERE pid='' AND owned='1'

**Comment by hitem** [comment]
Make sure the number %4 and %5 correspond with your med_gear and med_licenses, else switch them arround. Thats a house issue, you are using a SQL variable directly in your housescripts instead of pointing it to a [XXXXhouse] in the custom db ini

**Comment by Provokan** [comment]
Could you show me an example?

**Comment by hitem** [comment]
Yes, example would be if you used this "fix": (which dosent work for 4.0)
http://www.altisliferpg.com/topic/10245-fix-40-someone-already-owns-this-house-fix/
Where:
_query = format["SELECT pid, pos, inventory, containers FROM houses WHERE pid='%1' AND owned='1'",_this];
should be
_query = ([format["housingCheckHouse:%1", _housePos], 2] call DB_fnc_asyncCall) select 0;

(just an example)

**Comment by BAROD** [comment]
https://github.com/Itsyuka/Altis-Life/pull/114

**Pull request closed without merging**
