### PR TITLE
Update arma3life-4.0.sql

### PR DESCRIPTION
**Pull request by Ghostaunt**
Who made this database ... ?

Well, my optimisation is by the way better than original database.
I don't have time for edit sql queries and optimize more.

### CODE REVIEW

**Comment by chris579** [comment]
Dude, you didn't made optimizations... 
You left the ENUM unchanged (which is bs because enum is far greater than just a simple int and it is a char and not a int so it has to be parsed in sqf which is unnecessary)

You left the inventory column in vehicles db. It is not used...

You changed pid everywhere to char. This is not needed

**Comment by Ghostaunt** [comment]
"I don't have time for edit sql queries and optimize more."

Did you forget indexes ? 
Are you serious when you say "you didn't made optimizations"..

Yes it's better, not enought, but better than the original...
Funny boy.

**Comment by Ghostaunt** [comment]
And i'm agree for ENUM fileds.
Enum is very slow, but i have to check before if I change enum to tinyint if scripts always work well.

**Comment by trdwll** [comment]
If this is optimization then I guess I poop purple and it smells like rainbow sherbert.

The default sql file is fine, no need to update or "optimize" it. lol

**Comment by chris579** [comment]
Btw: primary key shouldn't be the playerid...

**Comment by Ghostaunt** [comment]
The default sql file is fine, no need to update or "optimize" it. lol

Ok...You guys have to learn how work a mysql database.

**Comment by chris579** [comment]
First:

The Altis Life default DB schmea is bs.

However, the db schema you want to merge is quite worse. 
It's bs to use pid as primary key.
You didn't made optimizations, you changed some datatypes (wuh, you're a magician)

**Comment by Ghostaunt** [comment]
Lol. Chris... You made my day ;) 
Thanks.

**Comment by chris579** [comment]
Sure, this is the original db. But if you are such a mySQL hero you would change this really quickly.

I don't care about strangers talking about my skill. I know what I can. And I know that our database is one of the best you can find in Altis Life. So, please, stfu.

**Comment by trdwll** [comment]
lel, I work with db's quite a bit. I'm also not sure how @chris579 and I comments are funny?
There really isn't any reason to update the sql due to the development on this not moving much. 

The last real commit was on Aug 29, 2015 by Shems-SA.

Sad to say, but this project is dead. Has been dead for months.

**Comment by m3talstorm** [comment]
There are a million and one much more substantial optimizations to do than tweaking the DB schema slightly. ;)

**Pull request closed without merging**
