### PR TITLE
Update fn_asyncCall.sqf

### PR DESCRIPTION
**Pull request by BAROD**
Torndeco give me just anytime this tip...

### CODE REVIEW

**Comment by Itsyuka** [comment]
:neckbeard: Ha, no

**Comment by BAROD** [comment]
Ehh ..;)

**Comment by Itsyuka** [comment]
I'll look into adding it in, just going to redo some things first

**Comment by Itsyuka** [comment]
Totally forgot that I didn't push your pull request, woops

**Comment by BAROD** [comment]
np :p already implemented https://github.com/Itsyuka/Altis-Life/blob/master/extDB-Build/life_server/Functions/MySQL/fn_asyncCall.sqf

**Pull request closed without merging**
