### PR TITLE
Should fix it

### PR DESCRIPTION
**Pull request by BAROD**

### CODE REVIEW

**Comment by manzarek123** [comment]
Didnt check if this worked but you should make a new fil in the gang folder and declare the function in config.cpp

**Comment by BAROD** [comment]
for what ?

**Comment by manzarek123** [comment]
ok nevermind i checked your change and you have no idea of what you are doing right?

[[player,grpPlayer],"TON_fnc_clientGangLeft",_unit,false] call life_fnc_MP;

You call the function  TON_fnc_clientGangLeft on _unit which is not even declared and what the fuck did you declare this function on the server to send it with a publicvariable you could just have paste that code in the gangleave file.

What i am saying makes no sense beacuse what you did makes even less sense

**Comment by Itsyuka** [comment]
He's right you know, should of just used "player"

**Comment by Itsyuka** [comment]
Also

**Comment by Itsyuka** [comment]
stop

**Comment by Itsyuka** [comment]
putting

**Comment by Itsyuka** [comment]
file

**Comment by Itsyuka** [comment]
changes

**Comment by Itsyuka** [comment]
like

**Comment by Itsyuka** [comment]
this

**Comment by BAROD** [comment]
wow okay...

**Comment by Itsyuka** [comment]
Cool, now we are on the same page

**Comment by ColinM9991** [comment]
Search this repository for life_my_gang, it's not used anymore.

**Comment by BAROD** [comment]
you right with this but i just copy this because it work and here is it still  https://github.com/Itsyuka/Altis-Life/blob/master/extDB-Build/life_server/functions.sqf#L60

**Pull request closed without merging**
