### PR TITLE
Adding Surrender to Official

### PR DESCRIPTION
**Pull request by KarmaLaBelle**
I went ahead and used MrKraken's Surrender Action script, and modified it to use the new macros. Thought this might be a good addition to the official repo. All credit goes to MrKraken, obviously.

### CODE REVIEW

**Comment by ColinM9991** [comment]
Update the Spyglass config to include life_fnc_surrender & life_fnc_surrender_meta and I'll merge these in

**Comment by BAROD** [comment]
fn_setupActions:

life_actions = life_actions + [player addAction[localize "STR_pAct_RobPerson",life_fnc_robAction,"",0,false,false,"",'

**Comment by BAROD** [comment]
https://github.com/Itsyuka/Altis-Life/pull/22

**Comment by KarmaLaBelle** [comment]
Closed, because BAROD did much better

**Pull request closed without merging**
